[versions]
agp = "8.9.0"
exoplayer = "2.19.1"
fadingedgelayout = "1.0.0"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.10.0"
multidex = "2.0.1"

[libraries]
exoplayer = { module = "com.google.android.exoplayer:exoplayer", version.ref = "exoplayer" }
fadingedgelayout = { module = "com.github.bosphere.android-fadingedgelayout:fadingedgelayout", version.ref = "fadingedgelayout" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }